"""Validation logic for video and subtitle pairs."""

from pathlib import Path
from typing import Optional, Tuple, List
import re

from logger_setup import get_logger
from models import SubtitleType


class PairValidator:
    """Validates that video and subtitle files form a valid pair."""
    
    # Minimum file sizes to consider valid (in bytes)
    MIN_VIDEO_SIZE = 10_000  # 10 KB minimum for video
    MIN_SUBTITLE_SIZE = 50   # 50 bytes minimum for subtitle
    
    # Video file extensions we accept
    VIDEO_EXTENSIONS = {".mp4", ".mkv", ".webm", ".m4v", ".mov", ".avi"}
    
    # Subtitle extensions we accept
    SUBTITLE_EXTENSIONS = {".srt", ".vtt", ".ass", ".ssa"}
    
    def __init__(self):
        self.logger = get_logger()
    
    def validate_pair(
        self,
        video_id: str,
        directory: Path,
        expected_subtitle_lang: str = "tr"
    ) -> Tuple[bool, Optional[Path], Optional[Path], SubtitleType, Optional[str]]:
        """
        Validate that a valid video+subtitle pair exists.
        
        Args:
            video_id: The video ID to look for
            directory: Directory to search in
            expected_subtitle_lang: Expected subtitle language code
        
        Returns:
            Tuple of:
                - is_valid: Whether a valid pair was found
                - video_path: Path to the video file (or None)
                - subtitle_path: Path to the subtitle file (or None)
                - subtitle_type: Type of subtitle found
                - error_message: Error description if invalid
        """
        video_path = self._find_video_file(video_id, directory)
        if video_path is None:
            return False, None, None, SubtitleType.NONE, "Video file not found"
        
        if not self._validate_video_file(video_path):
            return False, video_path, None, SubtitleType.NONE, "Video file is invalid or too small"
        
        subtitle_path, subtitle_type = self._find_subtitle_file(
            video_id, directory, expected_subtitle_lang
        )
        
        if subtitle_path is None:
            return False, video_path, None, SubtitleType.NONE, "Turkish subtitle file not found"
        
        if not self._validate_subtitle_file(subtitle_path):
            return False, video_path, subtitle_path, subtitle_type, "Subtitle file is invalid or empty"
        
        return True, video_path, subtitle_path, subtitle_type, None
    
    def _find_video_file(self, video_id: str, directory: Path) -> Optional[Path]:
        """Find a video file matching the video ID."""
        for ext in self.VIDEO_EXTENSIONS:
            candidate = directory / f"{video_id}{ext}"
            if candidate.exists():
                return candidate
        
        # Also check for files with language suffix (e.g., video_id.en.mp4)
        for file in directory.glob(f"{video_id}.*"):
            if file.suffix.lower() in self.VIDEO_EXTENSIONS:
                return file
        
        return None
    
    def _find_subtitle_file(
        self,
        video_id: str,
        directory: Path,
        lang_code: str = "tr"
    ) -> Tuple[Optional[Path], SubtitleType]:
        """
        Find a subtitle file matching the video ID and language.
        
        Returns tuple of (path, subtitle_type).
        Manual subtitles are preferred over auto-generated.
        """
        # Pattern for language code in filename
        # e.g., video_id.tr.srt, video_id.tr.vtt
        lang_patterns = [
            f"{video_id}.{lang_code}",  # video_id.tr.srt
            f"{video_id}.{lang_code}-orig",  # manual subtitle indicator
        ]
        
        # First, look for manual subtitles (no auto indicator)
        for ext in self.SUBTITLE_EXTENSIONS:
            for pattern in lang_patterns:
                candidate = directory / f"{pattern}{ext}"
                if candidate.exists():
                    # Check if it's auto-generated by looking at content or filename
                    if self._is_auto_generated(candidate):
                        continue
                    return candidate, SubtitleType.MANUAL
        
        # Then, look for any Turkish subtitle (including auto-generated)
        for ext in self.SUBTITLE_EXTENSIONS:
            for file in directory.glob(f"{video_id}*{ext}"):
                # Check if it contains Turkish language indicator
                if self._has_turkish_indicator(file.name):
                    subtitle_type = (
                        SubtitleType.AUTO_GENERATED 
                        if self._is_auto_generated(file) 
                        else SubtitleType.MANUAL
                    )
                    return file, subtitle_type
        
        return None, SubtitleType.NONE
    
    def _has_turkish_indicator(self, filename: str) -> bool:
        """Check if filename indicates Turkish language."""
        turkish_patterns = [
            r"\.tr\.", r"\.tr-", r"\.tur\.",  # Language codes
            r"\.turkish\.",  # Full name
        ]
        filename_lower = filename.lower()
        return any(re.search(pattern, filename_lower) for pattern in turkish_patterns)
    
    def _is_auto_generated(self, subtitle_path: Path) -> bool:
        """
        Determine if a subtitle file is auto-generated.
        
        Checks filename patterns and optionally content markers.
        """
        filename = subtitle_path.name.lower()
        
        # Common patterns for auto-generated subtitles from yt-dlp
        auto_patterns = [
            r"\.auto\.",
            r"-auto\.",
            r"_auto\.",
            r"\.a\.tr",  # yt-dlp sometimes uses this
        ]
        
        if any(re.search(pattern, filename) for pattern in auto_patterns):
            return True
        
        # Check content for auto-generated markers
        # YouTube auto-captions sometimes have specific patterns
        try:
            with open(subtitle_path, "r", encoding="utf-8", errors="ignore") as f:
                content = f.read(2000)  # Check first 2KB
                # Some auto-generated subs have timing precision markers
                if "align:start position:" in content:
                    return True
        except IOError:
            pass
        
        return False
    
    def _validate_video_file(self, video_path: Path) -> bool:
        """Validate that a video file is valid."""
        if not video_path.exists():
            return False
        
        size = video_path.stat().st_size
        if size < self.MIN_VIDEO_SIZE:
            self.logger.warning(
                f"Video file too small: {video_path} ({size} bytes)"
            )
            return False
        
        return True
    
    def _validate_subtitle_file(self, subtitle_path: Path) -> bool:
        """Validate that a subtitle file is valid."""
        if not subtitle_path.exists():
            return False
        
        size = subtitle_path.stat().st_size
        if size < self.MIN_SUBTITLE_SIZE:
            self.logger.warning(
                f"Subtitle file too small: {subtitle_path} ({size} bytes)"
            )
            return False
        
        # Basic content validation
        try:
            with open(subtitle_path, "r", encoding="utf-8", errors="ignore") as f:
                content = f.read(500)
                
            # SRT files should have timing patterns like "00:00:00,000 --> 00:00:01,000"
            # VTT files should have "WEBVTT" header or timing patterns
            if subtitle_path.suffix.lower() == ".srt":
                if not re.search(r"\d{2}:\d{2}:\d{2}", content):
                    self.logger.warning(f"SRT file missing timing markers: {subtitle_path}")
                    return False
            elif subtitle_path.suffix.lower() == ".vtt":
                if "WEBVTT" not in content and not re.search(r"\d{2}:\d{2}:\d{2}", content):
                    self.logger.warning(f"VTT file missing header/timing: {subtitle_path}")
                    return False
        except IOError as e:
            self.logger.warning(f"Failed to read subtitle file: {e}")
            return False
        
        return True
    
    def cleanup_failed_files(
        self,
        video_path: Optional[Path],
        subtitle_path: Optional[Path],
        delete: bool = True,
        failed_dir: Optional[Path] = None
    ) -> None:
        """
        Clean up files from a failed download.
        
        Args:
            video_path: Path to video file (may be None)
            subtitle_path: Path to subtitle file (may be None)
            delete: If True, delete files; if False, move to failed_dir
            failed_dir: Directory to move failed files to (if not deleting)
        """
        files_to_process = [p for p in [video_path, subtitle_path] if p and p.exists()]
        
        for file_path in files_to_process:
            try:
                if delete:
                    file_path.unlink()
                    self.logger.debug(f"Deleted failed file: {file_path}")
                elif failed_dir:
                    failed_dir.mkdir(parents=True, exist_ok=True)
                    dest = failed_dir / file_path.name
                    file_path.rename(dest)
                    self.logger.debug(f"Moved failed file to: {dest}")
            except IOError as e:
                self.logger.warning(f"Failed to clean up {file_path}: {e}")
